### ISSUE TITLE
source native_units from daemon

### ISSUE THREAD

**Issue by untzag** [wright-group/yaqc-cmds#306]
Currently required in config.

**Comment by ksunden** [comment]
I think we might go with something like `self.native_units = config.get("native_units", self.client.get_units())`

This is because I'd like to actually make native units optional _everywhere_, but delays in particular "native" is perhaps a bit of a misnomer... we want native to be "ps" (or at least "mm_delay") while the daemons are typically in "mm"

**Comment by untzag** [comment]
I think we require native_units for delays and disallow it everywhere else

**Comment by untzag** [comment]
do not like ambiguous behavior, or loosey goosey units
