### ISSUE TITLE
autonomic rough edges

### ISSUE THREAD

**Issue by untzag** [wright-group/yaqc-cmds#327]
1) In old state, autonomic tunes could be zeroed when delays are zeroed. This behavior is missing.

2) When arrangements are enabled or disabled there is unexpected behavior. 

3) Offsets must persist through restart.

**Comment by ksunden** [comment]
it is my belief that offsets _do_ persist through restart, or (if they don't show immediately, they should recompute upon setting, and should be correct, no?)

I'll test that out, but my first focus for this issue is on the zeroing behavior, I believe.
arrangements being enabled/disabled is rare enough that I'm not going to focus on it yet, though we should try to do so at some point.

**Comment by ksunden** [comment]
Okay, there is a problem with restarting, but it is that the zero position gets recorded with the offsets applied, but the positions are calcuated with zero position _without_ offsets applied, thus every restart progressively walks your zero position away from where it should be...

**Comment by ksunden** [comment]
I'm actually confused, I can see that the zero position changes when offsets are applied (as in the number changes when you do "set, (un)check autonomic box, set again")


but I can't see what is causing that, it should not be calling set_zero when setting the position...

**Comment by ksunden** [comment]
Okay, solved that riddle, the zero position _does_ change with offset, and it should.. storing and loading offset fixed the problem (though I think technically it is redundant information, it was the easiest solution for now)
